---
- name: Create new vm
  proxmox_kvm:
    name: player01.dev.cloudcenter.internal
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    clone: "ansi-client"
    storage: "local-lvm"
    target: "hetz"
    node: "hetz"
    timeout: 500
    description: created with ansible
  delegate_to: localhost
