---
- name: Create new vm
  proxmox:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    password: 123456
    #    hostname: "{{ inventory_hostname }}"
    hostname: example.com
    clone: "ansi-client"
    cores: 2
    cpu: 1
    full: true
    memory: 1024
    state: present
    description: created with ansible
  delegate_to: localhost
