---
- name: Create new vm
  community.general.proxmox:
    name: player01.dev.cloudcenter.internal
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    #    hostname: "{{ inventory_hostname }}"
    node: "hetz"
    clone: "ansi-client"
    cores: "2"
    cpu: "1"
    full: true
    memory: 1024
    state: present
    description: created with ansible
  delegate_to: localhost
